=begin
领签开发平台接口调试工具

\u6B64\u5DE5\u5177\u65E8\u5728\u5E2E\u52A9\u5F00\u53D1\u8005\u68C0\u6D4B\u8C03\u7528\u3010\u9886\u7B7E\u5F00\u53D1\u8005API\u3011\u65F6\u53D1\u9001\u7684\u8BF7\u6C42\u53C2\u6570\u662F\u5426\u6B63\u786E\uFF0C\u63D0\u4EA4\u76F8\u5173\u4FE1\u606F\u540E\u53EF\u83B7\u5F97\u670D\u52A1\u5668\u7684\u9A8C\u8BC1\u7ED3\u679C\u3002

OpenAPI spec version: 1.0.0
Contact: apiteam@linksign.cn
Generated by: https://github.com/swagger-api/swagger-codegen.git

License: Apache 2.0
http://www.apache.org/licenses/LICENSE-2.0.html


=end

require 'date'

module SwaggerClient
  # \u7B7E\u7F72\u4F4D\u7F6E\u4FE1\u606F
  class SignHere
    # \u7B7E\u540D\u6587\u4EF6\u7D22\u5F15\uFF0C \u4E0EDocument\u5BF9\u5E94
    attr_accessor :document_index

    # \u7B7E\u7F72\u533A\u57DF\u9AD8\u5EA6
    attr_accessor :height

    attr_accessor :page_number

    # \u7B7E\u7F72\u4EBA\u7D22\u5F15
    attr_accessor :recipient_index

    # \u5370\u7AE0\u9AD8\u5EA6
    attr_accessor :seal_height

    # \u5370\u7AE0\u7F16\u53F7
    attr_accessor :seal_id

    # \u5370\u7AE0\u9875\u7801
    attr_accessor :seal_page_number

    # \u5370\u7AE0\u5BBD\u5EA6
    attr_accessor :seal_width

    # \u5370\u7AE0X\u5750\u6807
    attr_accessor :seal_x_position

    # \u5370\u7AE0Y\u5750\u6807
    attr_accessor :seal_y_position

    # \u7B7E\u540D\u7F16\u53F7
    attr_accessor :signature_id

    # \u6A21\u677F\u516C\u7AE0\u5B57\u6BB5\u540D
    attr_accessor :template_seal_field_id

    # \u6A21\u677F\u7B7E\u540D\u5B57\u6BB5\u540D
    attr_accessor :template_signature_field_id

    # \u7B7E\u540D\u57DF\u5BBD\u5EA6
    attr_accessor :width

    # x\u5750\u6807
    attr_accessor :x_position

    # y\u5750\u6807
    attr_accessor :y_position

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        
        :'document_index' => :'documentIndex',
        
        :'height' => :'height',
        
        :'page_number' => :'pageNumber',
        
        :'recipient_index' => :'recipientIndex',
        
        :'seal_height' => :'sealHeight',
        
        :'seal_id' => :'sealId',
        
        :'seal_page_number' => :'sealPageNumber',
        
        :'seal_width' => :'sealWidth',
        
        :'seal_x_position' => :'sealXPosition',
        
        :'seal_y_position' => :'sealYPosition',
        
        :'signature_id' => :'signatureId',
        
        :'template_seal_field_id' => :'templateSealFieldId',
        
        :'template_signature_field_id' => :'templateSignatureFieldId',
        
        :'width' => :'width',
        
        :'x_position' => :'xPosition',
        
        :'y_position' => :'yPosition'
        
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'document_index' => :'String',
        :'height' => :'Integer',
        :'page_number' => :'Integer',
        :'recipient_index' => :'String',
        :'seal_height' => :'Integer',
        :'seal_id' => :'String',
        :'seal_page_number' => :'Integer',
        :'seal_width' => :'Integer',
        :'seal_x_position' => :'Integer',
        :'seal_y_position' => :'Integer',
        :'signature_id' => :'String',
        :'template_seal_field_id' => :'String',
        :'template_signature_field_id' => :'String',
        :'width' => :'Integer',
        :'x_position' => :'Integer',
        :'y_position' => :'Integer'
        
      }
    end

    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}

      
      if attributes[:'documentIndex']
        self.document_index = attributes[:'documentIndex']
      end
      
      if attributes[:'height']
        self.height = attributes[:'height']
      end
      
      if attributes[:'pageNumber']
        self.page_number = attributes[:'pageNumber']
      end
      
      if attributes[:'recipientIndex']
        self.recipient_index = attributes[:'recipientIndex']
      end
      
      if attributes[:'sealHeight']
        self.seal_height = attributes[:'sealHeight']
      end
      
      if attributes[:'sealId']
        self.seal_id = attributes[:'sealId']
      end
      
      if attributes[:'sealPageNumber']
        self.seal_page_number = attributes[:'sealPageNumber']
      end
      
      if attributes[:'sealWidth']
        self.seal_width = attributes[:'sealWidth']
      end
      
      if attributes[:'sealXPosition']
        self.seal_x_position = attributes[:'sealXPosition']
      end
      
      if attributes[:'sealYPosition']
        self.seal_y_position = attributes[:'sealYPosition']
      end
      
      if attributes[:'signatureId']
        self.signature_id = attributes[:'signatureId']
      end
      
      if attributes[:'templateSealFieldId']
        self.template_seal_field_id = attributes[:'templateSealFieldId']
      end
      
      if attributes[:'templateSignatureFieldId']
        self.template_signature_field_id = attributes[:'templateSignatureFieldId']
      end
      
      if attributes[:'width']
        self.width = attributes[:'width']
      end
      
      if attributes[:'xPosition']
        self.x_position = attributes[:'xPosition']
      end
      
      if attributes[:'yPosition']
        self.y_position = attributes[:'yPosition']
      end
      
    end

    # Check equality by comparing each attribute.
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          document_index == o.document_index &&
          height == o.height &&
          page_number == o.page_number &&
          recipient_index == o.recipient_index &&
          seal_height == o.seal_height &&
          seal_id == o.seal_id &&
          seal_page_number == o.seal_page_number &&
          seal_width == o.seal_width &&
          seal_x_position == o.seal_x_position &&
          seal_y_position == o.seal_y_position &&
          signature_id == o.signature_id &&
          template_seal_field_id == o.template_seal_field_id &&
          template_signature_field_id == o.template_signature_field_id &&
          width == o.width &&
          x_position == o.x_position &&
          y_position == o.y_position
    end

    # @see the `==` method
    def eql?(o)
      self == o
    end

    # Calculate hash code according to all attributes.
    def hash
      [document_index, height, page_number, recipient_index, seal_height, seal_id, seal_page_number, seal_width, seal_x_position, seal_y_position, signature_id, template_seal_field_id, template_signature_field_id, width, x_position, y_position].hash
    end

    # build the object from hash
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          else
            #TODO show warning in debug mode
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        else
          # data not found in attributes(hash), not an issue as the data can be optional
        end
      end

      self
    end

    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        _model = SwaggerClient.const_get(type).new
        _model.build_from_hash(value)
      end
    end

    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_body (backward compatibility))
    def to_body
      to_hash
    end

    # return the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Method to output non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
