=begin
领签开发平台接口调试工具

\u6B64\u5DE5\u5177\u65E8\u5728\u5E2E\u52A9\u5F00\u53D1\u8005\u68C0\u6D4B\u8C03\u7528\u3010\u9886\u7B7E\u5F00\u53D1\u8005API\u3011\u65F6\u53D1\u9001\u7684\u8BF7\u6C42\u53C2\u6570\u662F\u5426\u6B63\u786E\uFF0C\u63D0\u4EA4\u76F8\u5173\u4FE1\u606F\u540E\u53EF\u83B7\u5F97\u670D\u52A1\u5668\u7684\u9A8C\u8BC1\u7ED3\u679C\u3002

OpenAPI spec version: 1.0.0
Contact: apiteam@linksign.cn
Generated by: https://github.com/swagger-api/swagger-codegen.git

License: Apache 2.0
http://www.apache.org/licenses/LICENSE-2.0.html


=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/api_error'
require 'swagger_client/models/app'
require 'swagger_client/models/company'
require 'swagger_client/models/custom_fields'
require 'swagger_client/models/document'
require 'swagger_client/models/document_definition'
require 'swagger_client/models/document_status'
require 'swagger_client/models/document_summary'
require 'swagger_client/models/email_recipient'
require 'swagger_client/models/extra_recipients'
require 'swagger_client/models/id_auth'
require 'swagger_client/models/image_custom_field'
require 'swagger_client/models/personal'
require 'swagger_client/models/seal'
require 'swagger_client/models/seal_file'
require 'swagger_client/models/seal_summary'
require 'swagger_client/models/sign_date_time'
require 'swagger_client/models/sign_here'
require 'swagger_client/models/signature'
require 'swagger_client/models/signature_file'
require 'swagger_client/models/signature_summary'
require 'swagger_client/models/signer_status'
require 'swagger_client/models/signers'
require 'swagger_client/models/sms_recipient'
require 'swagger_client/models/tabs'
require 'swagger_client/models/text_custom_field'
require 'swagger_client/models/wechat_recipient'

# APIs
require 'swagger_client/api/document_api'
require 'swagger_client/api/seal_api'
require 'swagger_client/api/signature_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
